# Generated by Django 4.2.7 on 2023-11-05 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.user', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.user', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='staff_id',
            field=models.UUIDField(editable=False),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='SuperAdmin',
        ),
    ]
